spring:
  application:
    name: spring-jms-demo

tibco:
  server:
    url: "tibjmsnaming://tibjndi.example.com:7263"
    principal: <USERNAME>
    password: <PASSWORD>
  jndiName: DEMO.TEST.QUEUE

management:
  security:
    enabled: false
security:
  basic:
    enabled: false